name: Docker Debian

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t exporter -f ./docker/debian.Dockerfile .

      - name: Export binary to local fs
        run: cd /tmp && docker save exporter -o export.tar && mkdir -p export/layer && tar -xf export.tar --directory export && cd export && egrep -iwo '[a-z0-9\/]+layer.tar' manifest.json | tail -1 | xargs -n1 tar --directory layer -xf

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: npmci.debian-latest
          path: /tmp/export/layer/usr/bin/npmci
