name: Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]

    steps:
      - uses: actions/checkout@v1
      - name: update
        run: sudo apt update -qq && sudo apt install cmake make g++ -y -qq
      - name: clean
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S "." -B "./build"
      - name: build
        run: cmake --build "./build/" --target all -- -j 6;
      - name: test
        run: cd build && ctest
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: npmci.${{matrix.os}}
          path: build/npmci
